// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwlgkqdipcfvtzemhjku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3bGdrcWRpcGNmdnR6ZW1oamt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc4MTI0MzQsImV4cCI6MjA5MzM4ODQzNH0.ASpP4RUSXl_2ckO-IZ3TZG6CzaRRz3Bh_PkayW2P_Xg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
